name: mdt_fms_ptba
description: Offline-first MDT POC for mining fleet operations.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  drift: ^2.19.1
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.4.0
  dio: ^5.6.0
  connectivity_plus: ^6.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  clock: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  drift_dev: ^2.19.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
